a = "yolo is life man"
x = a.find ("yolo")
print(x)
y = a.find("life")
print(y)
z = a.replace ("yolo","YOLO")
print(z)
c = a.count("yolo")
print(c)
w = a.count("man")
print(w)
sm = a.partition('Yolo')
ms = a.split('yolo')
print(sm)
print(ms)
f = a.replace("yolo","GG")
print(f)
i = "we are here to learn python"
t = i.split() 
p = i.partition('World') 
print(t)
print(p)
abc = '-'.join(t)
print(abc)
s = "lol"
k = '^--^'.join(s)
print(k)
s = "Hello Python"
print(s)